### ISSUE TITLE
[Systemctl service won't start]

### ISSUE THREAD

**Issue by pierreCAMANALYTICS** [gitbls/sdm#180]
Hello Benn,

When trying to start a custome service, the service won't start :
![image](https://github.com/gitbls/sdm/assets/160324918/cb8c219b-fc9a-46c2-8e72-aa4f195c8e8f)

My service looks like this: 

![image](https://github.com/gitbls/sdm/assets/160324918/495c7629-a54c-4911-9a7d-b1f0f8228492)

But the bash command is working on my terminal.

This behavior is happening for all my customs services.

This is my customize script:
`
sdm --customize \
--extend --xmb 512 \
--plugin network:"netman=dhcpcd|wifissid=Livebox-49F7|wifipassword=********|wificountry=FR" \
--plugin copyfile:"filelist=/home/camanalytics/camanalytics/LampCam/images/base/files|mkdirif=yes" \
--plugin user:"adduser=pi" \
--plugin user:"setpassword=pi|password=pi" \
--plugin runatboot:"script=/home/camanalytics/camanalytics/LampCam/images/base/ref_files_v2/runatboot.sh|output=/home/pi/firsboot.log" \
--plugin raspiconfig:"spi=1" \
--plugin apps:"apps=@myapps|name=myapps" \
2023-05-03-raspios-bullseye-arm64-lite_base.img
`

I'm running v11.4

Am I'm missing something with the system plugin ?

Thank you

**Comment by pierreCAMANALYTICS** [comment]
Found the solution, by stopping **userconfig.service**

`sudo systemctl stop userconfig.service`

The service was stopping all other services that wanted to use **multi-user.target**

**Comment by gitbls** [comment]
Try NOT stopping/disabling the `userconfig` service, but instead use `--plugin disables:piwiz`. This will disable the userconfig service and a few other things that you don't need.

Also, a couple of other things:
* It doesn't hurt anything, but RasPiOS comes with the `pi` user already in /etc/passwd (but with no password set), so you don't need to `adduser=pi`. It doesn't hurt, of course, to leave it there
* In your camanalytics.service file, since you have specified `User=root` you don't need the `sudo` on the `ExecStart`

**Comment by gitbls** [comment]
Closing as resolved.
